package coreJava.streams;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

//https://www.geeksforgeeks.org/md5-hash-in-java/
//To calculate cryptographic hashing value in Java, MessageDigest Class is used, under the package java.security.
//This Algorithms are initialize in static method called getInstance().
// After selecting the algorithm it calculate the digest value and return the results in byte array.
public class CalculateMd5HashValue {
    public static void main(String[] args) throws NoSuchAlgorithmException {
        String s = "GeeksForGeeks";
        System.out.println("Your hashcode generated by MD5 is :"+ getMD5(s));
    }

    private static String getMD5(String s) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] messageDigest = md.digest(s.getBytes());
        BigInteger no = new BigInteger(1, messageDigest);
        String hashText = no.toString(16);
        while(hashText.length()<32){
            hashText = "0"+ hashText;
        }
        return hashText;

    }

}
