package string;
//A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
//
public class PrintAllSubsequencesOfAString {
    public static void main(String[] args) {

    }
}
